version: '2'

services:
  minio1:
    image: bitnami/minio:2023.9.23
    hostname: minio-test1.eappcat.com
    volumes:
      - /data:/bitnami/minio/data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=minio-test1.eappcat.com,minio-test2.eappcat.com,minio-test3.eappcat.com,minio-test4.eappcat.com
      - MINIO_SKIP_CLIENT=yes
