version: '3'
services:
  influxdb:
    image: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
    restart: always
  grafana:
    image: grafana/grafana:5.1.0
    ports:
      - "3000:3000"